# Generated by Django 2.1.3 on 2018-11-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam_assign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examassign',
            name='submitted_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
