# Generated by Django 2.1.3 on 2018-11-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('exam_assign', '0003_auto_20181124_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_assign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam_assign.ExamAssign')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Question')),
                ('user_ans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.Answer')),
            ],
        ),
    ]
